### ISSUE TITLE
Entwurf Kapitel KI & Gesellschaft erstellen

### ISSUE THREAD

**Issue by simondueckert** [cogneon/lernos-ai#10]
DoD: Entwurf des Kapitels mit einem Überblick über die gesellschaftlichen Implikationen von KI ist erstellt (KI Ethik, Arbeitsmarkt, Wettbewerbsfähigkeit, Mis/Disinformation etc.). Hierfür brauchen wir eine gute Quelle, die das gut zusammenfasst ([Hans-Boeckler-Paper von mspro](https://www.boeckler.de/de/faust-detail.htm?sync_id=HBS-008697)?).

**Comment by DoSchu-cowoxu** [comment]
Wir haben bei der Erstellung der Texte für diesen Bereich festgestellt, dass wir einen Stil wählen, der vielleicht nicht für die Grundlagen vorgesehen. Die MD-Datei konnten wir nicht im docs.de dauerhaft hochladen. Daher hänge ich sie hier an für die Diskussion am Freitag. 
[KI und Gesellschaft.md](https://github.com/cogneon/lernos-ai/files/13226549/KI.und.Gesellschaft.md)

**Comment by simondueckert** [comment]
Hmmmmm :) Der Inhalt gehört hier rein: https://github.com/cogneon/lernos-ai/blob/master/de/src/1-1-ai-history.md (in docs wird alles automatisch generiert).

**Comment by simondueckert** [comment]
Kapitel aus Sicht Team fertig, alle können bis nächstes Treffen noch Feedback geben, dann ist Kapitel fertig.

**Comment by simon-roderus** [comment]
Hey Kapitelteam👋,
echt beeindruckend, wie schnell ihr fertig wurdet 😯. Ich habe das Kapitel durchgelesen und habe ein paar Ideen, die ich gerne mit Euch teilen will. Hatte das in meinem Notizsystem aufgeschrieben und würde deshalb mit Euch den Link auf die Notizen teilen, wenn das für Euch in Ordnung ist?

Link: https://tana.pub/BJBGYtvqWAV-/feedback-zum-kapitel-ki-and-gesellschaft-absenden-am-today-mon-20-nov

**Comment by hgaertnerbr** [comment]
@simon-roderus Danke für Deine Kommentare und wir haben nochmals "gehirnt" und entsprechende Änderungen eingebaut! Beste Grüße von Hans und Doris

**Comment by simondueckert** [comment]
Aspekt der "Click-Sklaven" einbringen (Ethik)

**Comment by hgaertnerbr** [comment]
Ich habe ein paar Sätze zum Thema Click-Sklaven in den Absatz Ethik und Wertesysteme ergänzt und wir könnten noch zwei Links in die allgemeine Links Sammlung einfügen:
- einen  Tagesschau Artikel: https://www.tagesschau.de/wissen/technologie/ki-klickarbeiter-trainingsdaten-100.html
- einen Podcast vom SWR:https://www.swr.de/swr2/wissen/clickworker-ausgebeutet-fuer-kuenstliche-intelligenz-swr2-wissen-2023-08-24-102.html

**Comment by DoSchu-cowoxu** [comment]
Wir haben das Thema entsprechend im Text ergänzt und auch kurz Schutz des geistigen Eigentums in den Reflexionsfragen zu Ethik erweitert.

**Comment by hgaertnerbr** [comment]
Doris und Hans haben noch einen Aspekt ergänzt: Schutz des geistigen Eigentums in den Reflexionsfragen zu Ethik.
