### ISSUE TITLE
Top 100 AI Tools hinzufügen

### ISSUE THREAD

**Issue by simondueckert** [cogneon/lernos-ai#44]
Link https://www.flexos.work/ai-top-100 zu Weiterführende Infos und Kapitel KI Tools hinzufügen

**Comment by DoSchu-cowoxu** [comment]
Bin selten Fan dieser "Top"-Listen - diese zB. ist weltweit; Nutzwert für Interessierte aus Deutschland oder Europa daher eher gering. Wenn dann in _Weiterführende Infos_ ergänzen , nicht im _Kapitel KI Tools_ . Merci!

**Comment by simondueckert** [comment]
Gering würde ich nicht sagen, ChatGPT z.B. auf Platz 1 passt IMHO auch in DE. Habe den Link in Weiterführende Infos eingefügt, nicht im KI-Tool-Kapitel.
