### ISSUE TITLE
Entwurf Kapitel KI & Maschinelles Lernen erstellen

### ISSUE THREAD

**Issue by simondueckert** [cogneon/lernos-ai#5]
DoD: ein Entwurf des Kapitels mit einer Definition von Künstlicher Intelligenz, Machine Learning & Deep Learning (kuratieren, nicht "erfinden") ist erstellt.

**Comment by simondueckert** [comment]
- Positives Feedback: Mir gefällt das Beispiel mit dem Kind
- Vorschlag zur  Verbesserung: "Der gesamte Prozess kann als Kreislauf von insgesamt 7 Schritten dargestellt werden": da fehlt mir eine  Quelle? Außerdem ist Lernen [im Glossar](https://cogneon.github.io/lernos/de/lernos-glossary/#l) definiert als "der absichtliche oder beiläufige Erwerb von Wissen und Fähigkeiten. Lernen führt zu einer Veränderung des Verhaltens, Denkens oder Fühlens auf Basis neuer Erfahrungen oder Einsichten". Da ist mir der Kreis mit dem Startpunkt einer "Problemdefinition" und der "Datensammlung" zu eingeschränkt.
- Vorschlag zur  Verbesserung: Begriffe wie Deep Learning, Supervised/Unsupervised mit den (englischen) Wikipedia-Seiten verlinken
- Vorschlag zur  Verbesserung: vor das Beispiel sollte noch eine Darstellung und Beschreibung, wie KI und Maschinelles Lernen generell zusammenhängt. So ein Bild mit dem Beschreibungstext darunter: https://medium.com/swlh/artificial-intelligence-machine-learning-and-deep-learning-whats-the-real-difference-94fe7e528097

**Comment by simondueckert** [comment]
Vorschlag: wir erstellen für das Beispiel zum menschlichen vs. maschinellen Lernen in ein eigenes Kapitel und verwenden dieses Kapitel für das "Spiegelei". Habe das Gefühl, beides in einem Kapitel zusammen zu machen, ist vielleicht verwirrend?

**Comment by hgaertnerbr** [comment]
habe versucht, die Kapitel zu trennen und das "Spiegelei" in dem neuen Kapitel 1.2 zu beschreiben.
