### ISSUE TITLE
Entwurf Kapitel KI-Anwendungsfelder erstellen

### ISSUE THREAD

**Issue by simondueckert** [cogneon/lernos-ai#7]
DoD: Entwurf Anwendungsfelder aus technischer Perspektive (Text generieren) und aus Anwenderperspektive (Ankündigungs-Email erstellen) für KI ist erstellt.

**Comment by simondueckert** [comment]
Die [Klassifizierung der Modelle auf Hugging Face](https://huggingface.co/models) (linke Spalte) bildet die technische Perspektive ab. Siemens Healthineers und Telekom haben schöne Darstellungen für die Anwenderperspektive.

**Comment by MoMeissn** [comment]
> Würde hier gerne mitwirken 😄

Me too. 🙌

**Comment by simondueckert** [comment]
Zum Termin organisieren bin ich leider wegen zweier Veranstaltungen nicht gekommen, aber ich habe schonmal einen ersten Aufschlag für den Inhalt des Kapitels erstellt: https://cogneon.github.io/lernos-ai/de/1-4-ai-application-areas/
