### ISSUE TITLE
Entwurf Kapitel KI-Tools & Services erstellen

### ISSUE THREAD

**Issue by simondueckert** [cogneon/lernos-ai#9]
DoD: ein Entwurf für Kapitel mit einem Überblick über die wichtigsten Tools und Dienste ist erstellt. Eisberg-Ansatz: die Top X direkt benennen/beschreiben + Links zu guten Kuratierungen.

**Comment by DoSchu-cowoxu** [comment]
Recherchierte und bearbeitete Version ist hochgeladen. 

- Frage zu Glossar: Wird es ein spezifisches lernOS KI Glossar geben? 
- Unsere Lösung: Wir haben Begriffe in den Texten, die den jeweiligen Tool-Bereichen vorangestellt sind, Begriffe erklärt.

**Comment by simondueckert** [comment]
Simon legt Kapitel Glossar an.

**Comment by Ute2412** [comment]
Ich hatte hier in einer Umfrage auch ein paar der bekanntesten Tools aufgelistet. Könnt ja mal gegenchecken

Welche der nachfolgend aufgeführten Assistenzsysteme auf Basis generativer KI hast du schon einmal genutzt?
Text-Generatoren (ChatGPT, Bing, Claude, etc.)
Bild-Generatoren (DALL-E, Midjourney, Stable Diffusion, etc.)
Präsentations-Generatoren (Tome.AI, Beautiful.AI, etc.)
Video-Generatoren (Synthesia, HeyGen, FlexiClip, etc.)
Musik-Generatoren (Soundful, BeatBot, Splash Pro, etc.)
Code-Generatoren (GitHubCoPilot, Code Whisperer, etc.)

**Comment by DoSchu-cowoxu** [comment]
Ich erwähnte es im Call: ein never-ending chapter ;)

Die nicht behandelten Tools in dieser Liste arbeite ich durch, weil

- Kurze Liste
- User-Bekanntheit 

Dankeschön!

**Eine Bitte**

Sendet uns für das Kapitel keine langen Listen oder Links mit Linklisten zum Abgleichen, dafür ist das Zeitinvest hier schon zu groß gewesen.

Gerne nehmen wir hier konkrete Ergänzungen von Tools auf mit kurzer Begründung zB weil es eine DSGVO-konforme Lösung ist. 

Was uns besonders auffiel: Der Ease of use ist bei einigen Tools sehr zweifelhaft, und daher sind sie auch nicht hier im Kapitel drin.

Gracias

**Comment by Ute2412** [comment]
In der Kürze liegt die Würze. Wer noch mehr Tools braucht, kann ja dann auch weitergeleitet werden. Z.B. hier hin: [The 2023 MAD (ML/AI/Data) Landscape] [https://mad.firstmark.com/]

**Comment by DoSchu-cowoxu** [comment]
Mit letzten Überarbeitungen und Abbildung jetzt sozusagen fein für die erste Version. Danke Hans & Susann für die Mitarbeit!
